# Triggered on a schedule and manually via a dispatch event.
# This workflow test if the script is still working with the latest bo versions ('test').
# It also tests custom definable older script versions to determine if they still work
name: Test data upload script, triggered by bo changes or schedule
on:
  schedule:
    # Executes this workflow on a schedule (always uses the latest version on the default branch
    # (see: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule))
    # Execution on weekdays at 02:27 UTC
    - cron: "27 2 * * 1-5"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version_matrix: ${{ steps.set-version-matrix.outputs.version_matrix }}
    steps:
      - id: set-version-matrix
        # Define what versions should be regularly tested. An empty string means the latest commit (not release!).
        # (Versions must be defined by their git refs name, e. g. 'refs/tags/v1.0.0')
        #run: echo "::set-output name=matrix::['']"
        run: echo "version_matrix=['refs/tags/v1.1.0', '']" >> $GITHUB_OUTPUT

  # Short test on windows using PS7
  integration_test_short_windows_ps7:
    name: Short, Windows, PS7, version '${{ matrix.version }}'
    needs: [setup]
    runs-on: windows-2019
    strategy:
      matrix:
        version:
          - ${{fromJson(needs.setup.outputs.version_matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}
      - name: Status
        run: |
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Execute test
        shell: pwsh
        run: |
          echo "Test CSV import"


  # Short test on windows using PS5
  integration_test_short_windows_ps5:
    name: Short, Windows, PS5, version '${{ matrix.version }}'
    needs: [setup]
    runs-on: windows-2019
    strategy:
      matrix:
        version:
          - ${{fromJson(needs.setup.outputs.version_matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}
      - name: Status
        run: |
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Execute test
        shell: powershell
        run: |
          echo "Test CSV import"

  # Long test on ubuntu using PS7
  integration_test_short_ubuntu_ps7_mssql:
    name: Short, Ubuntu, PS7, mssql data source, version '${{ matrix.version }}'
    needs: [setup]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - ${{fromJson(needs.setup.outputs.version_matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}
      - name: Status
        run: |
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Execute test
        shell: pwsh
        run: |
          echo "Test MSSQL import"

  # Long test on ubuntu using PS7
  integration_test_long_ubuntu_ps7:
    name: Long, Ubuntu, PS7, version, batching enabled '${{ matrix.version }}'
    needs: [setup]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - ${{fromJson(needs.setup.outputs.version_matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}
      - name: Status
        run: |
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Execute test
        shell: pwsh
        run: |
          echo "Test CSV import"

  # Short test on ubuntu using PS7
  integration_test_short_ubuntu_ps7_no_batching:
    name: Short, Ubuntu, PS7, version, batching disabled '${{ matrix.version }}'
    needs: [setup]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - ${{fromJson(needs.setup.outputs.version_matrix)}}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.version }}
      - name: Status
        run: |
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Execute test
        shell: pwsh
        run: |
          echo "Test CSV import"
