# Triggered on push only.
# This workflow is for the development, when a new commit/tag/... is pushed the latest version for that branch is tested against the 'test' bo environment.
name: Test data upload script
on:
  push:

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    # Only run this job when a tag is pushed that starts with a 'v'
    # Goal is to refactor this job into another workflow. But that is not supported in the moment.
    # See: https://stackoverflow.com/questions/65324440/github-actions-using-workflow-run-based-on-new-tags
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install dependencies
        run: sudo npm install -g md-to-pdf@5.1.0
      - name: Convert markdown to pdf
        run: |
          sudo chmod +x ./.github/workflows/md_to_pdf.sh
          ./.github/workflows/md_to_pdf.sh '${{ github.ref_name }}'
      - name: Create release zip
        run: |
          sudo chmod +x ./.github/workflows/create-release.sh
          ./.github/workflows/create-release.sh ${{ github.event.repository.name }} ${{ github.ref_name }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.event.repository.name }}-release-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
